spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: posting
          uri: lb://posting-service
          predicates:
            - Path=/api/posting/**