spring:
  application:
    name: gateway-service-dev

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service-dev
          predicates:
            - Path=/api/user/**
          filters:
            - name: UserServiceFilter
              args:
                preLogger: true
                postLogger: true

        - id: auth
          uri: lb://user-service-dev
          predicates:
            - Path=/api/auth/**
          filters:
            - name: UserServiceFilter
              args:
                preLogger: true
                postLogger: true

        - id: posting
          uri: lb://posting-service-dev
          predicates:
            - Path=/api/posting/**
          filters:
            - name: PostingServiceFilter
              args:
                preLogger: true
                postLogger: true

        - id: common
          uri: lb://common-service-dev
          predicates:
            - Path=/api/common/**
          filters:
            - name: CommonServiceFilter
              args:
                preLogger: true
                postLogger: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka