server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: posting
          uri: lb://posting-service
          predicates:
            - Path=/api/posting/**