server:
  port: 8000

spring:
  profiles:
    active: pd

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true

jwt:
  secret: ${JWT_SECRET}